Repository Proyecto-ISPP/FISIOFIND, pull requests merged in 2025-05, with the labels that each got.

#573 docs: time report PPL
  docs/.img/projects_diagram_ppl.png
  docs/.img/users_diagram_ppl_1.png
  docs/.img/users_diagram_ppl_2.png
  docs/03_reports/time_reports/time_report_ppl.md
  docs/PPL/timeEffortReport.md
Labels: documentation

#571 Docs/knowledge base report ppl
  docs/05_knowledge_base/KB_reports/knowledge_base_report_ppl.md
  docs/05_knowledge_base/KB_reports/knowledge_base_report_s3.md
  docs/05_knowledge_base/feedback/feedback_28-03-2025.md
  docs/PPL/KBreport.md
  docs/PPL/commitmentAgreement.md
Labels: documentation

#578 Hotfix/arreglar eliminar cita
  frontend/app/patient-management/profile/page.tsx
  frontend/components/ui/appointment-modal.tsx
Labels: fix

#587 feat: creados archivos robots.txt para backend y frontend
  backend/fisio_find/fisio_find/urls.py
  frontend/public/robots.txt
Labels: enhancement

#592 feat: algo de seo
  frontend/app/layout.tsx
  frontend/static/og-cover.jpg
Labels: enhancement

#588 Docs/doc feedback 02 05
  docs/05_knowledge_base/feedback/feedback_02-05-2025.md
  docs/05_knowledge_base/feedback/feedback_11-04-2025.md
  docs/05_knowledge_base/feedback/feedback_25-04-2025.md
Labels: documentation

#589 Feat/subida archivos videos plan
  backend/fisio_find/appointment/migrations/__init__.py
  backend/fisio_find/appointment_rating/migrations/__init__.py
  backend/fisio_find/files/migrations/__init__.py
  backend/fisio_find/files/models.py
  backend/fisio_find/files/serializers.py
  backend/fisio_find/files/urls.py
  backend/fisio_find/files/views.py
  backend/fisio_find/fisio_find/exampledata.json
  backend/fisio_find/guest_session/migrations/__init__.py
  backend/fisio_find/payment/migrations/__init__.py
  backend/fisio_find/questionnaire/migrations/__init__.py
  backend/fisio_find/ratings/migrations/__init__.py
  backend/fisio_find/terms/migrations/__init__.py
  backend/fisio_find/treatments/migrations/__init__.py
  backend/fisio_find/users/migrations/__init__.py
  backend/fisio_find/videocall/migrations/__init__.py
  frontend/app/patient-management/follow-up/[id]/files/page.tsx
  frontend/app/patient-management/follow-up/[id]/videos/page.tsx
  frontend/app/physio-management/follow-up/[id]/files/page.tsx
  frontend/app/physio-management/follow-up/[id]/videos/page.tsx
Labels: enhancement, fix

#591 fix: arreglar bugs 11, 12, 13, 14, 15
  frontend/app/physio-management/follow-up/[id]/videos/page.tsx
Labels: fix

#594 fix: arreglado busqueda avanzada valoraciones estaba mocked
  backend/fisio_find/appointment_rating/admin.py
  backend/fisio_find/guest_session/views.py
  frontend/app/advanced-search/page.tsx
Labels: fix

#590 fix: solución bugs 1, 2, 3, 4 (Modulo: Registro paciente)
  backend/fisio_find/users/serializers.py
  backend/fisio_find/users/util.py
  frontend/app/register/patient/page.tsx
Labels: fix

#600 Hotfix/alguos errores en el deploy
  frontend/app/physio-management/balance/page.tsx
  frontend/app/physio-management/profile/page.tsx
  frontend/app/videocalls/page.tsx
Labels: fix

#601 docs: creado revision.md
  docs/WPL/revision.md
Labels: documentation

#607 fix: solucionar problema en despliegue con CORS
  backend/fisio_find/fisio_find/settings.py
Labels: fix, HIGH

#603 docs: KB report WPL
  docs/05_knowledge_base/KB_reports/knowledge_base_report_wpl.md
  docs/WPL/KBreport.md
Labels: documentation

#606 docs: time report wpl
  docs/.img/projects_diagram_wpl.png
  docs/.img/users_diagram_wpl_1.png
  docs/.img/users_diagram_wpl_2.png
  docs/03_reports/time_reports/time_report_wpl.md
  docs/WPL/timeEffortReport.md
Labels: documentation
