Repository Proyecto-ISPP/FISIOFIND, pull requests merged in 2025-04, with the labels that each got.

#412 Feature/videollamadas citas
  backend/fisio_find/appointment/views.py
  backend/fisio_find/videocall/models.py
  backend/fisio_find/videocall/serializers.py
  backend/fisio_find/videocall/urls.py
  backend/fisio_find/videocall/views.py
  frontend/app/videocalls/Controls.jsx
  frontend/app/videocalls/Room.jsx
  frontend/app/videocalls/Room.module.css
  frontend/app/videocalls/VideoGrid.jsx
  frontend/app/videocalls/hooks/useRoomManagement.js
  frontend/app/videocalls/page.tsx
Labels: enhancement

#428 Fix: añadida concordancia entre el serializer y el modelo de video
  backend/fisio_find/users/serializers.py
Labels: fix

#431 fix: Bugs sobre cuestionarios y servicios arreglados
  backend/fisio_find/users/urls.py
  backend/fisio_find/users/views.py
  frontend/app/physio-management/profile/page.tsx
  frontend/components/ui/Alert.tsx
  frontend/components/ui/ConfirmModal.tsx
  frontend/components/ui/WizardContent.tsx
Labels: fix

#440 feat: Reporte de ia para presentación del 04/04
  docs/03_reports/ia_reports/ia_report_week_9.md
Labels: documentation

#443 docs: documento de costes para el mid s3
  docs/02_planification/cost_tracking_document.md
Labels: documentation

#436 Feat/busqueda avanzada fisios
  backend/fisio_find/guest_session/urls.py
  backend/fisio_find/guest_session/views.py
  frontend/app/advanced-search/page.tsx
  frontend/app/page.tsx
  frontend/app/physio-management/profile/page.tsx
  frontend/app/videocalls/tools/body-highlighter/package-lock.json
  frontend/app/videocalls/tools/body-highlighter/package.json
  frontend/app/videocalls/tools/body-highlighter/yarn.lock
  frontend/components/sidebar-demo.tsx
  frontend/package-lock.json
Labels: enhancement, hu

#425 Feat/modificaciones perfil usuario
  backend/fisio_find/users/serializers.py
  frontend/app/register/page.tsx
  frontend/app/register/patient/page.tsx
  frontend/app/register/physio/page.tsx
Labels: enhancement

#409 Test/test unitarios
  .github/workflows/sonarqube.yml
  backend/fisio_find/appointment/exampledata.json
  backend/fisio_find/appointment/serializers.py
  backend/fisio_find/appointment/tests.py
  backend/fisio_find/appointment/urls.py
  backend/fisio_find/appointment/views.py
  backend/fisio_find/coverage.xml
  backend/fisio_find/payment/views.py
  backend/fisio_find/terms/tests.py
  backend/fisio_find/treatments/serializers.py
  backend/fisio_find/treatments/tests.py
  backend/fisio_find/users/admin.py
  backend/fisio_find/users/tests.py
  backend/fisio_find/users/urls.py
  backend/fisio_find/users/util.py
  backend/fisio_find/users/views.py
  frontend/app/physio-management/profile/page.tsx
  frontend/app/videocalls/tools/body-highlighter/yarn.lock
  frontend/components/CheckoutForm.tsx
  frontend/components/ui/AppointmentCalendar.tsx
  frontend/components/ui/ScheduleCalendar.tsx
  frontend/components/ui/Wizard.tsx
  frontend/components/ui/WizardContent.tsx
  frontend/components/ui/calendar.tsx
  frontend/lib/definitions.ts
  sonar-project.properties
Labels: enhancement

#446 Feat/seguimiento
  backend/fisio_find/fisio_find/settings.py
  backend/fisio_find/guest_session/migrations/__init__.py
  backend/fisio_find/treatments/admin.py
  backend/fisio_find/treatments/management/commands/send_exercise_reminders_local.py
  backend/fisio_find/treatments/management/commands/send_exercise_reminders_prod.py
  backend/fisio_find/treatments/models.py
  backend/fisio_find/treatments/serializers.py
  backend/fisio_find/treatments/urls.py
  backend/fisio_find/treatments/utils_reminder.py
  backend/fisio_find/treatments/views.py
  frontend/app/patient-management/follow-up/[id]/page.tsx
  frontend/app/patient-management/follow-up/[id]/sessions/[sessionId]/page.tsx
  frontend/app/patient-management/follow-up/[id]/sessions/page.tsx
  frontend/app/patient-management/follow-up/page.tsx
  frontend/app/physio-management/follow-up/[id]/page.tsx
  frontend/app/physio-management/follow-up/[id]/sessions/[sessionId]/exercises/page.tsx
  frontend/app/physio-management/follow-up/[id]/sessions/[sessionId]/tests/physio/page.tsx
  frontend/app/physio-management/follow-up/[id]/sessions/page.tsx
  frontend/app/physio-management/follow-up/page.tsx
  frontend/app/videocalls/page.tsx
  frontend/components/sidebar-demo.tsx
Labels: enhancement, hu

#427 Feat/subida imagenes y documentos
  backend/fisio_find/appointment/exampledata.json
  backend/fisio_find/appointment/views.py
  backend/fisio_find/files/__init__.py
  backend/fisio_find/files/admin.py
  backend/fisio_find/files/apps.py
  backend/fisio_find/files/migrations/__init__.py
  backend/fisio_find/files/models.py
  backend/fisio_find/files/serializers.py
  backend/fisio_find/files/tests.py
  backend/fisio_find/files/urls.py
  backend/fisio_find/files/views.py
  backend/fisio_find/fisio_find/settings.py
  backend/fisio_find/fisio_find/urls.py
  backend/fisio_find/treatments/models.py
  backend/fisio_find/users/admin.py
  backend/fisio_find/users/forms.py
  backend/fisio_find/users/models.py
  backend/fisio_find/users/permissions.py
  backend/fisio_find/users/serializers.py
  backend/fisio_find/users/tests.py
  backend/fisio_find/users/urls.py
  backend/fisio_find/users/util.py
  backend/fisio_find/users/validacionFisios.py
  backend/fisio_find/users/views.py
Labels: hu, HIGH

#441 Feat/ratings
  backend/fisio_find/appointment/exampledata.json
  backend/fisio_find/appointment/urls.py
  backend/fisio_find/fisio_find/settings.py
  backend/fisio_find/fisio_find/urls.py
  backend/fisio_find/ratings/__init__.py
  backend/fisio_find/ratings/admin.py
  backend/fisio_find/ratings/apps.py
  backend/fisio_find/ratings/migrations/__init__.py
  backend/fisio_find/ratings/models.py
  backend/fisio_find/ratings/serializers.py
  backend/fisio_find/ratings/tests.py
  backend/fisio_find/ratings/urls.py
  backend/fisio_find/ratings/views.py
  backend/fisio_find/users/emailUtils.py
  backend/fisio_find/users/models.py
  backend/fisio_find/users/urls.py
  backend/fisio_find/users/views.py
  frontend/app/page.tsx
  frontend/app/physio-management/profile/page.tsx
  frontend/app/register/verified/[token]/page.tsx
  frontend/components/ratings.module.css
  frontend/components/ratings.tsx
  frontend/components/ui/gradient-button.tsx
  next.config.js
Labels: enhancement, hu

#462 Feat/recordatorios ejercicios
  backend/fisio_find/treatments/management/commands/send_exercise_reminders_local.py
  backend/fisio_find/treatments/management/commands/send_exercise_reminders_prod.py
  backend/fisio_find/treatments/models.py
  backend/fisio_find/treatments/serializers.py
  backend/fisio_find/treatments/urls.py
  backend/fisio_find/treatments/utils_reminder.py
  backend/fisio_find/treatments/views.py
  frontend/app/globals.css
  frontend/app/patient-management/follow-up/[id]/page.tsx
  frontend/app/physio-management/profile/page.tsx
Labels: enhancement, hu

#454 Feat/cifrar dni
  backend/fisio_find/appointment/models.py
  backend/fisio_find/fisio_find/settings.py
  backend/fisio_find/payment/models.py
  backend/fisio_find/ratings/models.py
  backend/fisio_find/treatments/models.py
  backend/fisio_find/users/admin.py
  backend/fisio_find/users/models.py
  backend/requirements.txt
Labels: enhancement

#468 style: nuevo footer
  frontend/app/page.tsx
Labels: enhancement, LOW

#458 Style/busqueda avanzada
  backend/fisio_find/guest_session/admin.py
  backend/fisio_find/guest_session/serializers.py
  backend/fisio_find/guest_session/tests.py
  backend/fisio_find/guest_session/urls.py
  backend/fisio_find/guest_session/views.py
  frontend/app/advanced-search/page.tsx
  frontend/app/physio-management/profile/page.tsx
  frontend/components/sidebar-demo.tsx
  frontend/components/ui/3d-card.tsx
  frontend/components/ui/restore-filters.tsx
Labels: enhancement

#451 Fix/solucionar problema mapa dolor
  frontend/app/videocalls/Room.jsx
  frontend/app/videocalls/ToolPanel.jsx
  frontend/app/videocalls/tools/MapaDolor.jsx
  frontend/app/videocalls/tools/Templates.jsx
  frontend/app/videocalls/tools/body-highlighter/assets/bodyBack.ts
  frontend/app/videocalls/tools/body-highlighter/assets/bodyFemaleBack.ts
  frontend/app/videocalls/tools/body-highlighter/assets/bodyFemaleFront.ts
  frontend/app/videocalls/tools/body-highlighter/assets/bodyFront.ts
  frontend/app/videocalls/tools/body-highlighter/index.tsx
Labels: fix

#471 feat: fotos de perfil para usuarios
  backend/fisio_find/fisio_find/settings.py
  backend/fisio_find/fisio_find/urls.py
  backend/fisio_find/users/models.py
  frontend/app/page.tsx
  frontend/app/patient-management/profile/page.tsx
  frontend/app/physio-management/profile/page.tsx
  frontend/components/ratings.module.css
  frontend/components/ratings.tsx
  frontend/components/ui/physio-cta-adv.tsx
  frontend/components/ui/physio-cta.tsx
Labels: fix

#465 Feat/biblioteca ejercicios
  backend/fisio_find/treatments/urls.py
  backend/fisio_find/treatments/views.py
  backend/fisio_find/users/models.py
  frontend/app/physio-management/[id]/exercises/page.tsx
  frontend/app/physio-management/follow-up/[id]/page.tsx
  frontend/app/physio-management/follow-up/[id]/sessions/[sessionId]/tests/physio/page.tsx
  frontend/app/physio-management/profile/page.tsx
  frontend/static/images/body-regions/brazo.png
  frontend/static/images/body-regions/codo.png
  frontend/static/images/body-regions/core.png
  frontend/static/images/body-regions/cuadriceps.png
  frontend/static/images/body-regions/cuello.png
  frontend/static/images/body-regions/espalda.png
  frontend/static/images/body-regions/full_body.png
  frontend/static/images/body-regions/gemelos.png
  frontend/static/images/body-regions/gluteo.png
  frontend/static/images/body-regions/hombro.png
  frontend/static/images/body-regions/isquiotibiales.png
  frontend/static/images/body-regions/mano_muneca.png
  frontend/static/images/body-regions/pecho.png
  frontend/static/images/body-regions/pie_tobillo.png
  frontend/static/images/body-regions/rodilla.png
  frontend/static/images/body-regions/tren_inferior.png
  frontend/static/images/body-regions/tren_superior.png
  frontend/static/images/exercise-types/cardio.png
  frontend/static/images/exercise-types/coordinacion.png
  frontend/static/images/exercise-types/equilibrio.png
  frontend/static/images/exercise-types/estiramientos.png
  frontend/static/images/exercise-types/fuerza.png
  frontend/static/images/exercise-types/funcional.png
  frontend/static/images/exercise-types/movilidad.png
  frontend/static/images/exercise-types/propiocepcion.png
  frontend/static/images/exercise-types/respiracion.png
Labels: enhancement

#480 fix: restringiendo acceso a paginas register y login para usuarios au…
  frontend/app/login/page.tsx
  frontend/app/page.tsx
  frontend/app/register/page.tsx
  frontend/app/register/patient/page.tsx
  frontend/app/register/physio/page.tsx
Labels: enhancement, fix

#477 Feat/verificacion-id
  backend/fisio_find/users/urls.py
  backend/fisio_find/users/views.py
  frontend/app/register/patient/page.tsx
  frontend/app/register/physio/page.tsx
  frontend/components/IdentityVerificationStep.tsx
Labels: enhancement

#467 Feat/cuestionarios personalizados
  backend/fisio_find/fisio_find/settings.py
  backend/fisio_find/fisio_find/urls.py
  backend/fisio_find/questionnaire/__init__.py
  backend/fisio_find/questionnaire/admin.py
  backend/fisio_find/questionnaire/apps.py
  backend/fisio_find/questionnaire/migrations/__init__.py
  backend/fisio_find/questionnaire/models.py
  backend/fisio_find/questionnaire/serializers.py
  backend/fisio_find/questionnaire/tests.py
  backend/fisio_find/questionnaire/urls.py
  backend/fisio_find/questionnaire/views.py
  backend/fisio_find/users/admin.py
  backend/fisio_find/users/serializers.py
  backend/fisio_find/users/util.py
  frontend/app/questionnaires/Cuestionarios.jsx
  frontend/app/questionnaires/MyGroupRenderer.jsx
  frontend/app/questionnaires/page.tsx
  frontend/app/videocalls/Room.jsx
  frontend/app/videocalls/Room.module.css
  frontend/app/videocalls/ToolPanel.jsx
  frontend/app/videocalls/ToolsContainer.jsx
  frontend/app/videocalls/tools/PatientQuestionnaire.jsx
  frontend/app/videocalls/tools/QuestionnaireResponseViewer.jsx
  frontend/app/videocalls/tools/QuestionnaireTool.jsx
  frontend/components/sidebar-demo.tsx
  frontend/package-lock.json
  frontend/package.json
Labels: enhancement

#474 Docs/doc feedback 04 04
  docs/05_knowledge_base/feedback/feedback_04-04-2025.md
  docs/05_knowledge_base/feedback/feedback_28-03-2025.pdf
Labels: documentation

#479 feat: Vista de fisio antes de reservar
  backend/fisio_find/guest_session/views.py
  frontend/app/advanced-search/page.tsx
  frontend/components/ratings.tsx
  frontend/components/ui/PhysiotherapistModal.tsx
Labels: enhancement, hu

#478 Feat/verificación de correo electrónico
  backend/fisio_find/users/emailUtils.py
  backend/fisio_find/users/models.py
  backend/fisio_find/users/views.py
  frontend/app/register/patient/page.tsx
  frontend/app/register/verified/[token]/page.tsx
  frontend/package-lock.json
Labels: enhancement, fix, MEDIUM

#469 Hotfix: Cancelar recepción notificaciones
  backend/fisio_find/appointment/emailUtils.py
  backend/fisio_find/appointment/views.py
  backend/fisio_find/users/models.py
  backend/fisio_find/users/subscription_views.py
  backend/fisio_find/users/urls.py
  frontend/app/patient-management/profile/page.tsx
  frontend/app/physio-management/profile/page.tsx
  frontend/app/unsubscribe/page.tsx
  frontend/components/ui/SubscriptionSlider.tsx
Labels: enhancement

#473 Implementación de sistema de valoraciones de citas.
  backend/fisio_find/appointment_rating/__init__.py
  backend/fisio_find/appointment_rating/admin.py
  backend/fisio_find/appointment_rating/apps.py
  backend/fisio_find/appointment_rating/emailUtils.py
  backend/fisio_find/appointment_rating/migrations/__init__.py
  backend/fisio_find/appointment_rating/models.py
  backend/fisio_find/appointment_rating/serializers.py
  backend/fisio_find/appointment_rating/tests.py
  backend/fisio_find/appointment_rating/urls.py
  backend/fisio_find/appointment_rating/views.py
  backend/fisio_find/fisio_find/settings.py
  backend/fisio_find/fisio_find/urls.py
  frontend/app/physio-management/profile/page.tsx
  frontend/app/videocalls/end/page.tsx
  frontend/app/videocalls/page.tsx
  frontend/components/ui/AppointmentComment.tsx
  frontend/components/ui/EditableStarRatingDisplay.tsx
  frontend/components/ui/LoadingStar.css
  frontend/components/ui/PhysioterapistRating.tsx
  frontend/components/ui/RatingForm.tsx
  frontend/components/ui/StarRating.tsx
  frontend/components/ui/StarRatingDisplay.tsx
  frontend/components/ui/appointment-modal.tsx
  frontend/package-lock.json
  frontend/package.json
Labels: enhancement

#484 Feat/verificacion fisio
  backend/fisio_find/users/models.py
  backend/fisio_find/users/serializers.py
  frontend/app/physio-management/profile/page.tsx
Labels: MEDIUM

#481 Feat/solucionar problemas seguridad
  backend/fisio_find/users/admin.py
  backend/fisio_find/users/forms.py
  backend/fisio_find/users/models.py
  backend/fisio_find/users/serializers.py
  backend/fisio_find/users/tests.py
  backend/fisio_find/users/util.py
  frontend/ middleware.ts
  frontend/next.config.ts
Labels: enhancement

#488 feat: solucionar el problema de las claves de digital ocean en settin…
  backend/fisio_find/fisio_find/settings.py
Labels: MEDIUM

#452 Test/test unitarios
  .github/workflows/sonarqube.yml
  backend/fisio_find/appointment/tests.py
  backend/fisio_find/appointment/views.py
  backend/fisio_find/guest_session/tests.py
  backend/fisio_find/payment/models.py
  backend/fisio_find/payment/views.py
  backend/fisio_find/ratings/tests.py
  backend/fisio_find/ratings/views.py
  backend/fisio_find/users/util.py
  backend/fisio_find/videocall/tests.py
  backend/fisio_find/videocall/views.py
  frontend/app/videocalls/tools/body-highlighter/tsconfig.json.bak
  frontend/components/CheckoutForm.tsx
  frontend/components/ui/AppointmentCalendar.tsx
  frontend/lib/utils.ts
  frontend/package-lock.json
  frontend/package.json
Labels: testing

#489 Fix/solucionar videollamadas error si no dispositivos
  frontend/app/physio-management/profile/page.tsx
  frontend/app/videocalls/ChatPanel.jsx
  frontend/app/videocalls/Room.jsx
  frontend/app/videocalls/Room.module.css
  frontend/app/videocalls/hooks/useMediaControls.js
  frontend/app/videocalls/hooks/useWebRTC.js
  frontend/app/videocalls/hooks/useWebSocket.js
Labels: fix

#485 Feat/pagos y facturas
  backend/fisio_find/payment/models.py
  backend/fisio_find/payment/serializers.py
  backend/fisio_find/payment/urls.py
  backend/fisio_find/payment/utils/pdf_generator.py
  backend/fisio_find/payment/views.py
  backend/requirements.txt
  frontend/app/physio-management/balance/page.tsx
  frontend/app/physio-management/profile/page.tsx
Labels: enhancement, HIGH

#492 docs: creado plan de pruebas
  docs/02_planification/tests-plan.md
Labels: documentation

#495 test: suite de tests de appointment_ratings (alto coverage)
  backend/fisio_find/appointment_rating/tests.py
  backend/fisio_find/appointment_rating/urls.py
  backend/fisio_find/appointment_rating/views.py
Labels: testing

#498 docs: Time report sprint 3
  docs/.img/projects_diagram_sprint_3.png
  docs/.img/users_diagram_sprint_3_1.png
  docs/.img/users_diagram_sprint_3_2.png
  docs/03_reports/time_reports/time_report_sprint_2.pdf
  docs/03_reports/time_reports/time_report_sprint_3.md
Labels: documentation

#493 feat: readme actualizado S3
  README.md
Labels: enhancement

#499 Doc/reporte up sprint 3
  docs/03_reports/pilot_user_reports/sprint3_pilot_user_report.md
Labels: documentation

#501 Docs/knowledge base report s3
  docs/03_reports/time_reports/time_report_sprint_2.md
  docs/05_knowledge_base/KB_reports/knowledge_base_report_s3.md
  docs/SPRINT 3/KBreport.md
Labels: documentation

#505 docs: creado documento revision
  docs/SPRINT 3/revision.md
Labels: documentation

#475 feat: Hacer que un documento se pueda ver en la aplicación
  backend/.env.example
  backend/fisio_find/files/serializers.py
  backend/fisio_find/files/urls.py
  backend/fisio_find/files/views.py
  backend/fisio_find/fisio_find/settings.py
  backend/fisio_find/users/models.py
  frontend/app/patient-management/follow-up/[id]/files/page.tsx
  frontend/app/patient-management/follow-up/[id]/page.tsx
  frontend/app/patient-management/follow-up/[id]/videos/page.tsx
  frontend/app/patient-management/follow-up/page.tsx
  frontend/app/physio-management/follow-up/[id]/files/page.tsx
  frontend/app/physio-management/follow-up/[id]/page.tsx
  frontend/app/physio-management/follow-up/[id]/videos/page.tsx
  frontend/app/physio-management/video/page.tsx
  frontend/package-lock.json
  frontend/package.json
  package-lock.json
  package.json
Labels: hu, HIGH

#545 docs: creado LessonsLearnedS1.md
  docs/03_reports/LessonsLearnedS1.md
Labels: documentation

#536 docs: Primera versión feedback 11-04
  docs/05_knowledge_base/feedback/feedback_11-04-2025.md
Labels: documentation

#554 Fix/biblioteca ejercicios
  backend/fisio_find/treatments/models.py
  backend/fisio_find/treatments/views.py
  frontend/app/physio-management/[id]/exercises/page.tsx
  frontend/app/physio-management/follow-up/[id]/sessions/[sessionId]/exercises/page.tsx
  frontend/app/physio-management/follow-up/page.tsx
Labels: fix

#553 Doc/planning wpl
  docs/04_monitoring/sprint_4_ppl/sprint_planning_#PPL.md
  docs/04_monitoring/sprint_5_wpl/sprint_planning_#WPL.md
Labels: documentation

#568 Docs/doc feedback 25 04
  docs/05_knowledge_base/feedback/feedback_04-04-2025.md
  docs/05_knowledge_base/feedback/feedback_11-04-2025.md
  docs/05_knowledge_base/feedback/feedback_25-04-2025.md
Labels: documentation

#559 test: tests de selenium
  backend/selenium_tests/fisio find.side
  backend/selenium_tests/instrucciones.txt
Labels: enhancement

#570 Fix/arreglar conflictos bugs
  backend/fisio_find/appointment/tests.py
  backend/fisio_find/appointment_rating/tests.py
  backend/fisio_find/files/tests.py
  backend/fisio_find/fisio_find/settings.py
  backend/fisio_find/gestion_survey/__init__.py
  backend/fisio_find/gestion_survey/admin.py
  backend/fisio_find/gestion_survey/migrations/__init__.py
  backend/fisio_find/gestion_survey/models.py
  backend/fisio_find/gestion_survey/serializers.py
  backend/fisio_find/gestion_survey/urls.py
  backend/fisio_find/gestion_survey/views.py
  backend/fisio_find/guest_session/tests.py
  backend/fisio_find/guest_session/views.py
  backend/fisio_find/payment/tests.py
  backend/fisio_find/payment/urls.py
  backend/fisio_find/payment/views.py
  backend/fisio_find/terms/tests.py
  backend/fisio_find/treatments/tests.py
  backend/fisio_find/treatments/urls.py
  backend/fisio_find/users/emailUtils.py
  backend/fisio_find/users/serializers.py
  backend/fisio_find/users/tests.py
  backend/fisio_find/users/views.py
  backend/locust_tests/instrucciones.txt
  backend/locust_tests/locustfile-probar-muchas-urls.py
  backend/locust_tests/locustfile.py
  backend/requirements.txt
  frontend/app/confirm-alternative/[token]/page.tsx
  frontend/app/confirm-appointment/[token]/page.tsx
  frontend/app/patient-management/follow-up/[id]/videos/page.tsx
  frontend/app/patient-management/profile/page.tsx
  frontend/app/permissions-error/page.tsx
  frontend/app/physio-management/[id]/exercises/page.tsx
  frontend/app/physio-management/follow-up/[id]/page.tsx
  frontend/app/physio-management/follow-up/[id]/sessions/[sessionId]/exercises/page.tsx
  frontend/app/physio-management/follow-up/[id]/sessions/page.tsx
  frontend/app/physio-management/follow-up/[id]/videos/page.tsx
  frontend/app/physio-management/profile/page.tsx
  frontend/app/videocalls/Room.jsx
  frontend/app/videocalls/page.tsx
  frontend/components/ClientWrapper.tsx
  frontend/components/ui/AppointmentCalendar.tsx
  frontend/components/ui/appointment-modal.tsx
  frontend/package-lock.json
  frontend/package.json
Labels: fix
