Repository Proyecto-ISPP/FISIOFIND, pull requests merged in 2025-03, with the labels that each got.

#165 Feat/doc actualizacion registro requisitos
  docs/02_planification/requirements_registry.md
  docs/02_planification/requirements_registry.pdf
  docs/02_planification/user_stories_registry.md
Labels: documentation

#156 docs: documento feedback 21 de febrero
  docs/05_knowledge_base/feedback_21-02-2025.md
  docs/05_knowledge_base/feedback_21-02-2025.pdf
Labels: documentation

#164 doc añadir riesgo usuarios piloto
  docs/02_planification/risk_management_plan.md
  docs/02_planification/risk_management_plan.pdf
  docs/02_planification/risk_registry.md
  docs/02_planification/risk_registry.pdf
Labels: documentation

#169 docs: Plantilla del documento de Análisis cuantitativo de la calidad
  docs/03_reports/quality_reports/quality_report_06-03-2025.md
Labels: documentation

#172 Feat/acceso invitado
  .gitignore
  backend/fisio_find/fisio_find/settings.py
  frontend/app/globals.css
  frontend/app/layout.tsx
  frontend/app/page.tsx
  frontend/components.json
  frontend/components/3d-card-demo.tsx
  frontend/components/background-beams-aceternity.tsx
  frontend/components/sidebar-demo.tsx
  frontend/components/ui/3d-card.tsx
  frontend/components/ui/Modal.tsx
  frontend/components/ui/background-beams.tsx
  frontend/components/ui/focus-cards.tsx
  frontend/components/ui/lamp.tsx
  frontend/components/ui/sidebar.tsx
  frontend/lib/utils.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/static/10_race.webp
  frontend/static/11_health.webp
  frontend/static/1_heart.webp
  frontend/static/2_liftweights.webp
  frontend/static/3_ball.webp
  frontend/static/4_shine.webp
  frontend/static/5_russian.webp
  frontend/static/6_towel.webp
  frontend/static/7_treatment.webp
  frontend/static/8_guy.webp
  frontend/static/9_girl.webp
  frontend/static/fisio_find_logo.webp
  frontend/static/fisio_find_logo2.webp
  frontend/static/mock_up_01.webp
  frontend/static/mock_up_02.webp
  frontend/static/mock_up_03.webp
  frontend/static/mock_up_04.webp
  frontend/static/mock_up_05.webp
  frontend/tailwind.config.ts
  next.config.js
Labels: hu

#166 docs: Informe de tiempo semana 4
  docs/.img/projects_diagram_week_4.png
  docs/.img/users_diagram_week_4.png
  docs/03_reports/time_reports/time_report_week_4.md
Labels: documentation

#173 docs: Añadido reporte de ia semanas 4 y 5
  docs/03_reports/ia_reports/ia_report_week_4-5.md
Labels: documentation

#196 docs: actualización de commitment_agreement.md
  docs/.img/rejo_proyecto_06_03.png
  docs/01_organization/commitment_agreement.md
  docs/04_monitoring/sprint_1/mid_term_retrospective_#S1.md
Labels: documentation

#191 feat: terminado frontend y backend de admin para gestión de citas.
  backend/fisio_find/gestion_citas/urls.py
  backend/fisio_find/gestion_citas/views.py
  frontend/app/gestion-admin/citas/create/page.tsx
  frontend/app/gestion-admin/citas/delete/[id]/page.tsx
  frontend/app/gestion-admin/citas/edit/[id]/page.tsx
  frontend/app/gestion-admin/citas/page.tsx
  frontend/app/gestion-admin/citas/view/[id]/page.tsx
  frontend/app/gestion-admin/page.tsx
Labels: enhancement

#198 feat: Registro fisios con validación (Via API)
  backend/fisio_find/fisio_find/settings_postman.py
  backend/fisio_find/gestion_usuarios/migrations/0005_remove_physiotherapist_account_status_and_more.py
  backend/fisio_find/gestion_usuarios/models.py
  backend/fisio_find/gestion_usuarios/serializers.py
  backend/fisio_find/gestion_usuarios/urls.py
  backend/fisio_find/gestion_usuarios/validacionFisios.py
  backend/fisio_find/gestion_usuarios/views.py
Labels: enhancement

#224 Feat/doc riesgos cambio nuevos
  docs/02_planification/risk_management_plan.md
  docs/02_planification/risk_registry.md
Labels: documentation

#228 Feat/doc gestion usuarios piloto
  README.md
  docs/.img/pilot_users/edad_pacientes.png
  docs/.img/pilot_users/especialidades_fisioterapeutas.png
  docs/.img/pilot_users/experiencia_fisioterapeutas.png
  docs/.img/pilot_users/frecuencia_consulta.png
  docs/.img/pilot_users/lugar_trabajo_fisios.png
  docs/.img/pilot_users/motivos_consulta.png
  docs/.img/pilot_users/prioridades_pacientes.png
  docs/01_organization/commitment_agreement.md
  docs/01_organization/individual-performance-evaluation-form.md
  docs/01_organization/pilot_user_agreement.md
  docs/02_planification/backend_formation_plan.md
  docs/02_planification/pilot_user_management_plan.md
  docs/02_planification/user_stories_registry.md
  docs/03_reports/pilot_user_reports/sprint1_pilot_user_report.md
  docs/03_reports/time_reports/time_report_week_4.md
  docs/03_reports/time_reports/time_report_week_5.md
  docs/03_reports/time_reports/time_report_week_5.pdf
  docs/04_monitoring/meetings/meeting_08-03-2025.md
  docs/04_monitoring/meetings/meeting_22-02-2025.md
  docs/04_monitoring/meetings/meeting_25-02-2025.md
  docs/04_monitoring/sprint_1/mid_term_retrospective_#S1.md
  docs/build-pdf-examples.sh
Labels: documentation, hu

#233 docs: Feedback del 07/03/2025
  docs/05_knowledge_base/feedback_07-03-2025.md
Labels: documentation

#232 docs: Actualizacion documento de costes.
  docs/.img/caso-optimista.png
  docs/.img/caso-pesimista.png
  docs/.img/caso-realista.png
  docs/02_planification/configuration_management_plan.md
  docs/02_planification/cost_breakdown.md
  docs/02_planification/cost_tracking_document.md
Labels: documentation, enhancement

#227 Feat/admin mejora estilo y seguridad
  backend/fisio_find/gestion_citas/serializers.py
  backend/fisio_find/gestion_terminos/serializers.py
  backend/fisio_find/gestion_terminos/views.py
  backend/fisio_find/gestion_usuarios/serializers.py
  backend/fisio_find/gestion_usuarios/urls.py
  backend/fisio_find/gestion_usuarios/views.py
  frontend/app/gestion-admin/citas/create/page.tsx
  frontend/app/gestion-admin/citas/delete/[id]/page.tsx
  frontend/app/gestion-admin/citas/edit/[id]/page.tsx
  frontend/app/gestion-admin/citas/page.tsx
  frontend/app/gestion-admin/citas/view/[id]/page.tsx
  frontend/app/gestion-admin/globals.css
  frontend/app/gestion-admin/layout.tsx
  frontend/app/gestion-admin/page.tsx
  frontend/app/gestion-admin/terminos/create/page.tsx
  frontend/app/gestion-admin/terminos/delete/[id]/page.tsx
  frontend/app/gestion-admin/terminos/edit/[id]/page.tsx
  frontend/app/gestion-admin/terminos/page.tsx
  frontend/app/gestion-admin/terminos/view/[id]/page.tsx
  frontend/app/gestion-admin/usuarios/fisioterapeutas/create/page.tsx
  frontend/app/gestion-admin/usuarios/fisioterapeutas/delete/[id]/page.tsx
  frontend/app/gestion-admin/usuarios/fisioterapeutas/edit/[id]/page.tsx
  frontend/app/gestion-admin/usuarios/fisioterapeutas/view/[id]/page.tsx
  frontend/app/gestion-admin/usuarios/pacientes/create/page.tsx
  frontend/app/gestion-admin/usuarios/pacientes/delete/[id]/page.tsx
  frontend/app/gestion-admin/usuarios/pacientes/edit/[id]/page.tsx
  frontend/app/gestion-admin/usuarios/pacientes/page.tsx
  frontend/app/gestion-admin/usuarios/pacientes/view/[id]/page.tsx
  frontend/app/gestion-admin/usuarios/page.tsx
Labels: enhancement

#236 Fix/doc actualizacion plan gestion cambio
  docs/01_organization/pilot_user_agreement.md
  docs/02_planification/change_management_plan.md
  docs/02_planification/configuration_management_plan.md
  docs/02_planification/cost_tracking_document.md
  docs/02_planification/pilot_user_management_plan.md
  docs/02_planification/risk_management_plan.md
  docs/02_planification/risk_registry.md
  docs/03_reports/ia_reports/ia_report_week_4-5.md
  docs/03_reports/quality_reports/quality_report_06-03-2025.md
  docs/03_reports/time_reports/time_report_week_3.md
  docs/04_monitoring/sprint_1/sprint_planning_#1.md
  docs/05_knowledge_base/feedback_07-03-2025.md
  docs/05_knowledge_base/feedback_21-02-2025.md
Labels: documentation

#229 Feat/busqueda avanzada
  backend/fisio_find/fisio_find/settings.py
  backend/fisio_find/fisio_find/urls.py
  backend/fisio_find/gestion_citas/migrations/0001_initial.py
  backend/fisio_find/gestion_citas/migrations/0002_initial.py
  backend/fisio_find/gestion_terminos/migrations/0001_initial.py
  backend/fisio_find/gestion_terminos/migrations/0002_initial.py
  backend/fisio_find/gestion_usuarios/migrations/0001_initial.py
  backend/fisio_find/gestion_usuarios/migrations/0002_alter_appuser_options_alter_appuser_managers_and_more.py
  backend/fisio_find/gestion_usuarios/migrations/0003_remove_patient_age_patient_birth_date.py
  backend/fisio_find/gestion_usuarios/migrations/0004_admin.py
  backend/fisio_find/gestion_usuarios/migrations/0005_remove_physiotherapist_account_status_and_more.py
  backend/fisio_find/gestion_usuarios/models.py
  backend/fisio_find/gestion_usuarios/serializers.py
  backend/fisio_find/gestion_usuarios/views.py
  backend/fisio_find/sesion_invitado/__init__.py
  backend/fisio_find/sesion_invitado/admin.py
  backend/fisio_find/sesion_invitado/apps.py
  backend/fisio_find/sesion_invitado/models.py
  backend/fisio_find/sesion_invitado/serializers.py
  backend/fisio_find/sesion_invitado/tests.py
  backend/fisio_find/sesion_invitado/urls.py
  backend/fisio_find/sesion_invitado/views.py
  frontend/app/globals.css
  frontend/app/layout.tsx
  frontend/app/page.tsx
  frontend/components/ui/AnimatedIcons.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/static/fisio_find_logo2.webp
  frontend/static/fisioterapeuta_sample.jpeg
  frontend/static/logo_fisio_find_smaller.PNG
  frontend/static/search.svg
  frontend/tailwind.config.ts
  package-lock.json
Labels: hu

#226 Feat/videollamada
  backend/fisio_find/fisio_find/asgi.py
  backend/fisio_find/fisio_find/settings.py
  backend/fisio_find/fisio_find/urls.py
  backend/fisio_find/gestion_citas/exampledata.json
  backend/fisio_find/gestion_citas/views.py
  backend/fisio_find/videocall/__init__.py
  backend/fisio_find/videocall/admin.py
  backend/fisio_find/videocall/apps.py
  backend/fisio_find/videocall/consumers.py
  backend/fisio_find/videocall/migrations/0001_initial.py
  backend/fisio_find/videocall/migrations/__init__.py
  backend/fisio_find/videocall/models.py
  backend/fisio_find/videocall/routes.py
  backend/fisio_find/videocall/routing.py
  backend/fisio_find/videocall/serializers.py
  backend/fisio_find/videocall/tests.py
  backend/fisio_find/videocall/urls.py
  backend/fisio_find/videocall/views.py
  backend/requirements.txt
  frontend/app/globals.css
  frontend/app/mis-citas/mis-citas.css
  frontend/app/mis-citas/page.tsx
  frontend/app/videollamadas/ChatPanel.jsx
  frontend/app/videollamadas/Controls.jsx
  frontend/app/videollamadas/Room.jsx
  frontend/app/videollamadas/Room.module.css
  frontend/app/videollamadas/RoomHeader.jsx
  frontend/app/videollamadas/RoomModal.jsx
  frontend/app/videollamadas/SettingsPanel.jsx
  frontend/app/videollamadas/ToolPanel.jsx
  frontend/app/videollamadas/ToolsContainer.jsx
  frontend/app/videollamadas/VideoGrid.jsx
  frontend/app/videollamadas/[roomCode]/page.jsx
  frontend/app/videollamadas/hooks/useChat.js
  frontend/app/videollamadas/hooks/useMediaControls.js
  frontend/app/videollamadas/hooks/useRoomManagement.js
  frontend/app/videollamadas/hooks/useWebRTC.js
  frontend/app/videollamadas/hooks/useWebSocket.js
  frontend/app/videollamadas/page.tsx
  frontend/app/videollamadas/tools/Cuestionarios.jsx
  frontend/app/videollamadas/tools/Historial.jsx
  frontend/app/videollamadas/tools/Modelo3D.jsx
  frontend/app/videollamadas/tools/Plantillas.jsx
  frontend/components/sidebar-demo.tsx
  frontend/components/ui/calendar.tsx
  frontend/components/ui/cards.tsx
  frontend/lib/definitions.ts
  frontend/package-lock.json
  frontend/package.json
Labels: enhancement

#243 Hotfix/sprint 1
  .github/ISSUE_TEMPLATE/request_for_change.md
  .gitignore
  README.md
  backend/fisio_find/gestion_usuarios/migrations/0002_alter_appuser_photo.py
  frontend/app/page.tsx
  frontend/app/register/patient/page.tsx
Labels: enhancement

#242 fix: correciones de frontend para demo
  backend/fisio_find/gestion_usuarios/migrations/0002_alter_appuser_photo.py
  frontend/app/page.tsx
  frontend/app/register/patient/page.tsx
Labels: enhancement

#244 docs: Reporte de ia Sprint 1
  docs/03_reports/ia_reports/ia_report_Sprint-1.md
Labels: documentation

#240 Feat/perfil fisio
  backend/fisio_find/fisio_find/settings.py
  backend/fisio_find/gestion_usuarios/migrations/0006_alter_appuser_photo.py
  backend/fisio_find/gestion_usuarios/models.py
  backend/fisio_find/gestion_usuarios/serializers.py
  backend/fisio_find/gestion_usuarios/urls.py
  backend/fisio_find/gestion_usuarios/views.py
  frontend/app/gestion-fisio/perfil/page.tsx
  frontend/app/gestion-fisio/perfil/photo.scss
  frontend/app/gestion-paciente/perfil/page.tsx
  frontend/app/globals.css
  frontend/app/page.tsx
  frontend/components/sidebar-demo.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/public/default_avatar.png
Labels: enhancement

#249 docs: Retrospectiva Sprint 1-G1
  docs/04_monitoring/sprint_1/sprint_retrospective.md
Labels: documentation

#246 Feat/doc knowledge base report sprint 1
  docs/02_planification/requirements_registry.md
  docs/04_monitoring/sprint_1/sprint_retrospective_grupo_2.md
  docs/05_knowledge_base/feedback_07-03-2025.md
  docs/05_knowledge_base/knowledge_base_report_s1.md
  docs/SPRINT 1/KBreport.md
Labels: documentation

#252 Feat/corregir errores citas
  backend/fisio_find/gestion_citas/exampledata.json
  backend/fisio_find/gestion_citas/migrations/0001_initial.py
  backend/fisio_find/gestion_citas/migrations/0002_initial.py
  backend/fisio_find/gestion_terminos/migrations/0001_initial.py
  backend/fisio_find/gestion_terminos/migrations/0002_initial.py
  backend/fisio_find/gestion_usuarios/migrations/0001_initial.py
  backend/fisio_find/gestion_usuarios/migrations/0002_alter_appuser_photo.py
  backend/fisio_find/gestion_usuarios/migrations/0006_alter_appuser_photo.py
  frontend/app/mis-citas/page.tsx
  frontend/components/ui/appointment-modal.tsx
  frontend/components/ui/calendar.tsx
Labels: enhancement, hu

#253 Feat/fisio calendario
  backend/fisio_find/gestion_citas/migrations/0001_initial.py
  backend/fisio_find/gestion_citas/migrations/0002_initial.py
  backend/fisio_find/gestion_terminos/migrations/0001_initial.py
  backend/fisio_find/gestion_terminos/migrations/0002_initial.py
  backend/fisio_find/gestion_usuarios/migrations/0001_initial.py
  backend/fisio_find/gestion_usuarios/serializers.py
  backend/fisio_find/gestion_usuarios/views.py
  frontend/app/gestion-fisio/perfil/page.tsx
  frontend/components/ui/ScheduleCalendar.tsx
  frontend/lib/definitions.ts
  frontend/lib/utils.ts
Labels: enhancement

#304 docs: elaboración de sprint planning #S2
  docs/02_planification/user_stories_registry.md
  docs/04_monitoring/sprint_1/sprint_planning_#1.md
  docs/04_monitoring/sprint_2/mid_term_retrospective_#S2.md
  docs/04_monitoring/sprint_2/sprint_planning_#2.md
Labels: documentation

#305 fix: eliminado trigger de workflow de despliegue
  .github/workflows/feat-deploy_fisiofind-backend.yml
Labels: enhancement

#307 Hotfix/corregir errores citas
  backend/fisio_find/gestion_citas/urls.py
  backend/fisio_find/gestion_citas/views.py
  frontend/app/mis-citas/page.tsx
  frontend/components/ui/AppointmentCalendar.tsx
  frontend/components/ui/Wizard.tsx
  frontend/components/ui/appointment-modal.tsx
  frontend/components/ui/calendar.tsx
  frontend/components/ui/cards.tsx
  frontend/lib/utils.ts
Labels: enhancement

#310 Feat/citas calendario
  backend/fisio_find/gestion_citas/urls.py
  backend/fisio_find/gestion_citas/views.py
  frontend/app/mis-citas/mis-citas.css
  frontend/app/mis-citas/page.tsx
  frontend/components/ui/appointment-modal.tsx
  frontend/components/ui/calendar.tsx
  frontend/components/ui/cards.tsx
  frontend/lib/utils.ts
Labels: enhancement

#319 docs: Reporte de ia semana 7 (Primera iteración Sprint 2)
  docs/03_reports/ia_reports/ia_report_week_7.md
Labels: documentation

#320 docs/cambios commitment agreement
  docs/01_organization/commitment_agreement.md
Labels: documentation

#309 Hotfix/corregir perfil fisio
  .github/workflows/feat-deploy_fisiofind-backend.yml
  backend/fisio_find/gestion_usuarios/validacionFisios.py
  backend/fisio_find/gestion_usuarios/views.py
  frontend/app/physio-management/profile/page.tsx
Labels: enhancement

#313 docs: Feedback 14-03-2025
  docs/05_knowledge_base/feedback_14-03-2025.md
Labels: documentation

#315 Hotfix/fix videollamadas
  frontend/app/videocalls/Room.jsx
  frontend/app/videocalls/hooks/useRoomManagement.js
  frontend/app/videocalls/hooks/useWebRTC.js
Labels: enhancement

#326 feat: Enviar notificaciones relevantes a usuarios
  backend/.env.example
  backend/fisio_find/fisio_find/settings.py
  backend/fisio_find/gestion_citas/emailUtils.py
  backend/fisio_find/gestion_citas/exampledata.json
  backend/fisio_find/gestion_citas/urls.py
  backend/fisio_find/gestion_citas/views.py
  frontend/app/confirm-appointment/[token]/page.tsx
Labels: enhancement

#318 Feat/cuestionario preintervencion
  backend/fisio_find/gestion_usuarios/serializers.py
  backend/fisio_find/gestion_usuarios/urls.py
  backend/fisio_find/gestion_usuarios/views.py
  frontend/app/appointments/create/[id]/page.tsx
  frontend/components/ui/ServiceQuestionary.tsx
  frontend/components/ui/Wizard.tsx
  frontend/components/ui/WizardContent.tsx
  frontend/context/appointmentContext.tsx
  frontend/lib/definitions.ts
Labels: enhancement

#328 fix: solucionados errores de rutas para entornos y de vistas
  backend/fisio_find/sesion_invitado/urls.py
  frontend/app/page.tsx
  frontend/components/ui/Wizard.tsx
Labels: fix

#332 fix: se ha arreglado la forma en la que se traen las especializaciones y el logo de la home page
  frontend/app/page.tsx
  frontend/static/logo_fisio_find_smaller.webp
Labels: fix

#334 docs: corrección y ampliación de algunos apartados de service_level_a…
  docs/01_organization/service_level_agreement.md
Labels: documentation

#331 Feat/mapa dolor
  frontend/app/page.tsx
  frontend/app/videocalls/Room.jsx
  frontend/app/videocalls/ToolPanel.jsx
  frontend/app/videocalls/hooks/3DModel.js
  frontend/app/videocalls/tools/MapaDolor.jsx
  frontend/app/videocalls/tools/Templates.jsx
  frontend/app/videocalls/tools/body-highlighter/LICENSE
  frontend/app/videocalls/tools/body-highlighter/README.md
  frontend/app/videocalls/tools/body-highlighter/assets/bodyBack.ts
  frontend/app/videocalls/tools/body-highlighter/assets/bodyFemaleBack.ts
  frontend/app/videocalls/tools/body-highlighter/assets/bodyFemaleFront.ts
  frontend/app/videocalls/tools/body-highlighter/assets/bodyFront.ts
  frontend/app/videocalls/tools/body-highlighter/components/SvgFemaleWrapper.tsx
  frontend/app/videocalls/tools/body-highlighter/components/SvgMaleWrapper.tsx
  frontend/app/videocalls/tools/body-highlighter/index.tsx
  frontend/app/videocalls/tools/body-highlighter/package-lock.json
  frontend/app/videocalls/tools/body-highlighter/package.json
  frontend/app/videocalls/tools/body-highlighter/rn-cli.config.js
  frontend/app/videocalls/tools/body-highlighter/tsconfig.json
  frontend/app/videocalls/tools/body-highlighter/yarn.lock
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/static/logo_fisio_find_smaller.webp
Labels: enhancement

#338 Feat/Perfil paciente arreglado
  backend/fisio_find/gestion_usuarios/serializers.py
  frontend/app/globals.css
  frontend/app/patient-management/profile/page.tsx
  frontend/app/patient-management/profile/photo.css
Labels: fix

#342 Feat/refactorizacion backend
  backend/fisio_find/fisio_find/settings.py
  backend/fisio_find/fisio_find/urls.py
  backend/fisio_find/gestion_citas/exampledata.json
  backend/fisio_find/gestion_citas/migrations/0001_initial.py
  backend/fisio_find/gestion_citas/migrations/0002_initial.py
  backend/fisio_find/gestion_citas/models.py
  backend/fisio_find/gestion_citas/serializers.py
  backend/fisio_find/gestion_citas/views.py
  backend/fisio_find/guest_session/__init__.py
  backend/fisio_find/guest_session/admin.py
  backend/fisio_find/guest_session/apps.py
  backend/fisio_find/guest_session/models.py
  backend/fisio_find/guest_session/serializers.py
  backend/fisio_find/guest_session/tests.py
  backend/fisio_find/guest_session/urls.py
  backend/fisio_find/guest_session/views.py
  backend/fisio_find/terms/migrations/0001_initial.py
  backend/fisio_find/terms/migrations/0002_alter_terms_tag.py
  backend/fisio_find/terms/migrations/0002_initial.py
  backend/fisio_find/terms/models.py
  backend/fisio_find/terms/views.py
  backend/fisio_find/users/__init__.py
  backend/fisio_find/users/admin.py
  backend/fisio_find/users/apps.py
  backend/fisio_find/users/migrations/0001_initial.py
  backend/fisio_find/users/migrations/__init__.py
  backend/fisio_find/users/models.py
  backend/fisio_find/users/permissions.py
  backend/fisio_find/users/serializers.py
  backend/fisio_find/users/tests.py
  backend/fisio_find/users/urls.py
  backend/fisio_find/users/util.py
  backend/fisio_find/users/validacionFisios.py
  backend/fisio_find/users/views.py
  frontend/app/page.tsx
  frontend/app/patient-management/profile/page.tsx
Labels: fix

#346 Rfc/integrar usuarios videollamadas
  frontend/app/videocalls/Room.jsx
  frontend/app/videocalls/hooks/useRoomManagement.js
  frontend/app/videocalls/page.tsx
Labels: fix

#341 docs: Documento de feedback 21/03
  docs/05_knowledge_base/feedback_21-03-2025.md
Labels: documentation

#347 feat: funcionalidad de admin para que pueda gestionar las citas termi…
  backend/fisio_find/gestion_citas/urls.py
  backend/fisio_find/gestion_citas/views.py
  backend/fisio_find/users/serializers.py
  backend/fisio_find/users/urls.py
  backend/fisio_find/users/views.py
  frontend/app/admin-management/appointments/create/page.tsx
  frontend/app/admin-management/appointments/delete/[id]/page.tsx
  frontend/app/admin-management/appointments/edit/[id]/page.tsx
  frontend/app/admin-management/appointments/page.tsx
  frontend/app/admin-management/appointments/view/[id]/page.tsx
Labels: enhancement

#349 Style/refactorizacion frontend
  Users/antoniommff/Library/CloudStorage/OneDrive-UNIVERSIDADDESEVILLA/INGENIERÍA DEL SOFTWARE/〽️ 4 INGENIERÍA DEL SOFTWARE/4 SEGUNDO CUATRIMESTRE/ispp/Trabajo semanal/S08/Antonio_weekly_work.md
  backend/fisio_find/gestion_citas/migrations/0001_initial.py
  backend/fisio_find/gestion_citas/migrations/0002_initial.py
  backend/fisio_find/terms/migrations/0001_initial.py
  backend/fisio_find/terms/migrations/0002_initial.py
  backend/fisio_find/users/migrations/0001_initial.py
  backend/fisio_find/users/serializers.py
  backend/fisio_find/users/urls.py
  backend/fisio_find/users/views.py
  backend/fisio_find/videocall/migrations/0001_initial.py
  backend/requirements.txt
  frontend/app/layout.tsx
  frontend/app/my-appointments/page.tsx
  frontend/app/page.tsx
  frontend/app/patient-management/profile/page.tsx
  frontend/app/physio-management/profile/page.tsx
  frontend/app/physio-management/profile/photo.css
  frontend/app/physio-management/profile/photo.scss
  frontend/app/register/patient/page.tsx
  frontend/app/videocalls/Room.jsx
  frontend/app/videocalls/hooks/useRoomManagement.js
  frontend/app/videocalls/hooks/useWebRTC.js
  frontend/app/videocalls/page.tsx
  frontend/components/demo-window.tsx
  frontend/components/service-create-modal.tsx
  frontend/components/service-edit-modal.tsx
  frontend/components/sidebar-demo.tsx
  frontend/components/ui/appointment-modal.tsx
  frontend/components/ui/calendar.css
  frontend/components/ui/calendar.tsx
  frontend/components/ui/gradient-button.tsx
  frontend/components/ui/lamp.tsx
  frontend/components/ui/sidebar.tsx
  frontend/components/ui/wavy-background.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/tailwind.config.ts
  package-lock.json
  package.json
Labels: hu, fix

#343 Feat/tratamiento tests
  backend/fisio_find/fisio_find/settings.py
  backend/fisio_find/fisio_find/urls.py
  backend/fisio_find/gestion_citas/migrations/0001_initial.py
  backend/fisio_find/gestion_citas/migrations/0002_initial.py
  backend/fisio_find/gestion_survey/__init__.py
  backend/fisio_find/gestion_survey/admin.py
  backend/fisio_find/gestion_survey/models.py
  backend/fisio_find/gestion_survey/serializers.py
  backend/fisio_find/gestion_survey/urls.py
  backend/fisio_find/gestion_survey/views.py
  backend/fisio_find/terms/migrations/0001_initial.py
  backend/fisio_find/terms/migrations/0002_initial.py
  backend/fisio_find/treatments/__init__.py
  backend/fisio_find/treatments/admin.py
  backend/fisio_find/treatments/migrations/0001_initial.py
  backend/fisio_find/treatments/migrations/__init__.py
  backend/fisio_find/treatments/models.py
  backend/fisio_find/treatments/serializers.py
  backend/fisio_find/treatments/urls.py
  backend/fisio_find/treatments/views.py
  backend/fisio_find/users/migrations/0001_initial.py
  backend/fisio_find/videocall/migrations/0001_initial.py
  frontend/app/physio-management/follow-up/[id]/page.tsx
  frontend/app/physio-management/follow-up/[id]/sessions/[sessionId]/exercises/page.tsx
  frontend/app/physio-management/follow-up/[id]/sessions/page.tsx
  frontend/app/physio-management/follow-up/components/FilterBar.tsx
  frontend/app/physio-management/follow-up/components/TreatmentCard.tsx
  frontend/app/physio-management/follow-up/page.tsx
  frontend/app/videocalls/tools/Questionnaires.jsx
  frontend/components/sidebar-demo.tsx
  frontend/package-lock.json
  frontend/package.json
  package-lock.json
  package.json
Labels: enhancement

#354 fix: Herramientas en videollamada para paciente
  frontend/app/videocalls/Room.jsx
Labels: fix

#357 Feat/admin sistema
  backend/fisio_find/fisio_find/settings.py
  backend/fisio_find/users/admin.py
  backend/fisio_find/users/forms.py
  backend/fisio_find/users/serializers.py
  backend/fisio_find/users/urls.py
  backend/fisio_find/users/views.py
  frontend/app/admin-management/appointments/create/page.tsx
  frontend/app/admin-management/appointments/delete/[id]/page.tsx
  frontend/app/admin-management/appointments/edit/[id]/page.tsx
  frontend/app/admin-management/appointments/page.tsx
  frontend/app/admin-management/appointments/view/[id]/page.tsx
  frontend/app/admin-management/favicon.ico
  frontend/app/admin-management/globals.css
  frontend/app/admin-management/layout.tsx
  frontend/app/admin-management/page.tsx
  frontend/app/admin-management/terms/create/page.tsx
  frontend/app/admin-management/terms/delete/[id]/page.tsx
  frontend/app/admin-management/terms/edit/[id]/page.tsx
  frontend/app/admin-management/terms/page.tsx
  frontend/app/admin-management/terms/view/[id]/page.tsx
  frontend/app/admin-management/users/page.tsx
  frontend/app/admin-management/users/patients/create/page.tsx
  frontend/app/admin-management/users/patients/delete/[id]/page.tsx
  frontend/app/admin-management/users/patients/edit/[id]/page.tsx
  frontend/app/admin-management/users/patients/page.tsx
  frontend/app/admin-management/users/patients/view/[id]/page.tsx
  frontend/app/admin-management/users/physios/create/page.tsx
  frontend/app/admin-management/users/physios/delete/[id]/page.tsx
  frontend/app/admin-management/users/physios/edit/[id]/page.tsx
  frontend/app/admin-management/users/physios/page.tsx
  frontend/app/admin-management/users/physios/view/[id]/page.tsx
  frontend/app/admin-management/util.tsx
  frontend/components/sidebar-demo.tsx
  frontend/package-lock.json
  package.json
Labels: enhancement

#355 Feat/subida archivos
  backend/custom_storage.py
  backend/fisio_find/fisio_find/settings.py
  backend/fisio_find/guest_session/models.py
  backend/fisio_find/guest_session/urls.py
  backend/fisio_find/guest_session/views.py
  backend/fisio_find/treatments/migrations/0004_merge_0002_initial_0003_alter_session_day_of_week.py
  backend/fisio_find/users/migrations/0002_video.py
  backend/fisio_find/users/models.py
  backend/fisio_find/users/serializers.py
  backend/fisio_find/users/urls.py
  backend/fisio_find/users/views.py
  backend/requirements.txt
  backend/users/migrations/0002_video.py
  frontend/app/layout.tsx
  frontend/app/page.tsx
  frontend/app/patient-management/video/page.tsx
  frontend/app/physio-management/video/page.tsx
  package-lock.json
  package.json
Labels: enhancement

#358 Hotfix/edicion perfil fisio
  backend/fisio_find/users/serializers.py
  backend/fisio_find/users/urls.py
  backend/fisio_find/users/views.py
  frontend/app/globals.css
  frontend/app/layout.tsx
  frontend/app/login/page.tsx
  frontend/app/my-appointments/page.tsx
  frontend/app/patient-management/profile/page.tsx
  frontend/app/physio-management/profile/page.tsx
  frontend/app/physio-management/profile/photo.css
  frontend/app/terms/page.tsx
  frontend/components/ClientWrapper.tsx
  frontend/components/ui/ServiceQuestionary.tsx
  frontend/components/ui/Wizard.tsx
  frontend/components/ui/WizardContent.tsx
  frontend/components/ui/WizardNavigation.tsx
  frontend/components/ui/appointment-modal.tsx
  frontend/context/appointmentContext.tsx
  frontend/lib/definitions.ts
  frontend/public/photo.css
  package.json
Labels: hu

#367 docs: Reporte de ia del Sprint 2
  docs/03_reports/ia_reports/ia_report_Sprint-2.md
Labels: documentation

#372 Hotfix/boton editar eliminar servicio
  frontend/app/physio-management/profile/page.tsx
Labels: fix

#373 feat: añadidos buscadores a paneles de admin de paciente, fisio y app…
  backend/fisio_find/appointment/admin.py
  backend/fisio_find/users/admin.py
Labels: enhancement

#370 feat:borrados mockups de vista videollamadas
  frontend/app/videocalls/Room.module.css
  frontend/app/videocalls/ToolsContainer.jsx
  frontend/app/videocalls/tools/Templates.jsx
Labels: enhancement

#377 feat: añadida opcion de busqueda para ejercicios, sesiones, tratamien…
  backend/fisio_find/payment/admin.py
  backend/fisio_find/treatments/admin.py
Labels: enhancement

#382 Hotfix/boton apartado videos
  backend/fisio_find/users/serializers.py
  frontend/app/patient-management/profile/page.tsx
  frontend/app/physio-management/profile/page.tsx
  frontend/app/physio-management/video/page.tsx
  frontend/package-lock.json
Labels: enhancement

#381 docs: primera version de la revision guide del s2
  docs/03_reports/security_reports/security_report.md
  docs/SPRINT 2/revision.md
Labels: documentation

#403 Docs: Acta reunión G3 15-03-2025
  docs/04_monitoring/meetings/meeting_15-03-2025.md
Labels: documentation

#404 Feat/solucionar vulnerabilidades dependencias
  backend/requirements.txt
  frontend/app/videocalls/tools/body-highlighter/package-lock.json
Labels: fix

#405 docs: sprint planning 3 terminado
  docs/04_monitoring/sprint_3/sprint_planning_#3.md
Labels: documentation, epic

#411 Create SECURITY.md
  SECURITY.md
Labels: documentation
